'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace TrackITKTS

    Partial Public Class frmAddEditEmptyKegReturn_CusToBP

        '''<summary>
        '''chkSession control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSession As Global.KEG_X.TrackITKTS.chkUserpresent

        '''<summary>
        '''RadScriptManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

        '''<summary>
        '''addATSEmployees control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents addATSEmployees As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''TABLE100 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TABLE100 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''TABLE1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TABLE1 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rcbFromCmpny control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbFromCmpny As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''rfvrdcCmpnny control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvrdcCmpnny As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divCustomer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divCustomer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtCustomer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCustomer As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hdfCustomerID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfCustomerID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''AutoCompleteExtender_txtCustomer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AutoCompleteExtender_txtCustomer As Global.AjaxControlToolkit.AutoCompleteExtender

        '''<summary>
        '''RequiredFieldValidator2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Label7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rcbToCmpny control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbToCmpny As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''rfvrcToCmpny control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvrcToCmpny As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divToBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divToBP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtToBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToBP As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hdfToBPID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfToBPID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''AutoCompleteExtender_txtToBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AutoCompleteExtender_txtToBP As Global.AjaxControlToolkit.AutoCompleteExtender

        '''<summary>
        '''RequiredFieldValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtTransactionNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTransactionNumber As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''Label3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dpCollectionDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dpCollectionDate As Global.Telerik.Web.UI.RadDatePicker

        '''<summary>
        '''RequiredFieldValidator7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator7 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblItemID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblItemID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divItems As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtItemCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hdfItemID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfItemID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''txtItemCode_AutoCompleteExtender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemCode_AutoCompleteExtender As Global.AjaxControlToolkit.AutoCompleteExtender

        '''<summary>
        '''txtItemID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemID As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''RequiredFieldValidator3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblItemDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblItemDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtItemDesc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemDesc As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''RequiredFieldValidator4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Label4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtItemName2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemName2 As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''RequiredFieldValidator9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator9 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblQuantity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblQuantity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtQuantity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtQuantity As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''RequiredFieldValidator5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''RegularExpressionValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''lblUOM control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUOM As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtUOM control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUOM As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''RequiredFieldValidator6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator6 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Label6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSerialNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSerialNo As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''btnAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAdd As Global.Telerik.Web.UI.RadButton

        '''<summary>
        '''RadgvEmptyKegTransfer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadgvEmptyKegTransfer As Global.Telerik.Web.UI.RadGrid

        '''<summary>
        '''radSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radSave As Global.Telerik.Web.UI.RadButton

        '''<summary>
        '''radClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radClear As Global.Telerik.Web.UI.RadButton

        '''<summary>
        '''radCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radCancel As Global.Telerik.Web.UI.RadButton

        '''<summary>
        '''ValidationSummary1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''ValidationSummary2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary2 As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''ObjDSCustomers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjDSCustomers As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''ObjBranchPlant control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjBranchPlant As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
