'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace TrackITKTS

    Partial Public Class frmAddEditReceiveEmptyKeg_BPtoBP1

        '''<summary>
        '''chkSession control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSession As Global.KEG_X.TrackITKTS.chkUserpresent

        '''<summary>
        '''RadScriptManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

        '''<summary>
        '''addATSEmployees control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents addATSEmployees As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''TABLE100 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TABLE100 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''TABLE1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TABLE1 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rcbFromCmpny control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbFromCmpny As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''rfvrdcCmpnny control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvrdcCmpnny As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divFromBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divFromBP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtFromBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFromBP As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hdfFromBPID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfFromBPID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''AutoCompleteExtender_txtFromBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AutoCompleteExtender_txtFromBP As Global.AjaxControlToolkit.AutoCompleteExtender

        '''<summary>
        '''RequiredFieldValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Label7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rcbToCmpny control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbToCmpny As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''rfvrcToCmpny control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvrcToCmpny As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divToBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divToBP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtToBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToBP As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hdfToBPID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfToBPID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''AutoCompleteExtender_txtToBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AutoCompleteExtender_txtToBP As Global.AjaxControlToolkit.AutoCompleteExtender

        '''<summary>
        '''RequiredFieldValidator2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Label3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rcbTransactionNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbTransactionNumber As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''RequiredFieldValidator3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''btnShow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnShow As Global.Telerik.Web.UI.RadButton

        '''<summary>
        '''RadgvEmptyKegReceive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadgvEmptyKegReceive As Global.Telerik.Web.UI.RadGrid

        '''<summary>
        '''radSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radSave As Global.Telerik.Web.UI.RadButton

        '''<summary>
        '''radClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radClear As Global.Telerik.Web.UI.RadButton

        '''<summary>
        '''radCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radCancel As Global.Telerik.Web.UI.RadButton

        '''<summary>
        '''ValidationSummary1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''ValidationSummary2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary2 As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''ObjBranchPlant control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjBranchPlant As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''ObjEmptyKegsReceiveBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjEmptyKegsReceiveBP As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''objTransactionNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents objTransactionNumber As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
