'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace TrackITKTS

    Partial Public Class frmEmptyKegReceive_BPtoBP

        '''<summary>
        '''chkSession control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSession As Global.KEG_X.TrackITKTS.chkUserpresent

        '''<summary>
        '''RadScriptManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''RadButton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadButton1 As Global.Telerik.Web.UI.RadButton

        '''<summary>
        '''Literal1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Literal1 As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''upnl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upnl As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''TABLE1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TABLE1 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''Table2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table2 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''Table6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table6 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblFromBranchPlantCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFromBranchPlantCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divFromBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divFromBP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtFromBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFromBP As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hdfFromBPID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfFromBPID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''AutoCompleteExtender_txtFromBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AutoCompleteExtender_txtFromBP As Global.AjaxControlToolkit.AutoCompleteExtender

        '''<summary>
        '''lblToBranchPlantCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblToBranchPlantCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divToBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divToBP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtToBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToBP As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hdfToBPID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfToBPID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''AutoCompleteExtender_txtToBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AutoCompleteExtender_txtToBP As Global.AjaxControlToolkit.AutoCompleteExtender

        '''<summary>
        '''Table3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table3 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblItemCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblItemCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divItemCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divItemCode As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtItemCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hdfItemCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfItemCode As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''AutoCompleteExtender_txtItemCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AutoCompleteExtender_txtItemCode As Global.AjaxControlToolkit.AutoCompleteExtender

        '''<summary>
        '''lblStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rtbStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rtbStatus As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''lblTransactionId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTransactionId As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rtbTransactionId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rtbTransactionId As Global.Telerik.Web.UI.RadTextBox

        '''<summary>
        '''radSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radSearch As Global.Telerik.Web.UI.RadButton

        '''<summary>
        '''radClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents radClear As Global.Telerik.Web.UI.RadButton

        '''<summary>
        '''RadgvEmptyKegTransfer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadgvEmptyKegTransfer As Global.Telerik.Web.UI.RadGrid

        '''<summary>
        '''ObjEmptyKegsReceiveBP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjEmptyKegsReceiveBP As Global.System.Web.UI.WebControls.ObjectDataSource

        '''<summary>
        '''ObjBranchPlant control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ObjBranchPlant As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
