'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace TrackITKTS

    Partial Public Class NewSearch

        '''<summary>
        '''sm1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sm1 As Global.System.Web.UI.ScriptManager

        '''<summary>
        '''txtGoingTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtGoingTo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtGoingTo_AutoCompleteExtender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtGoingTo_AutoCompleteExtender As Global.AjaxControlToolkit.AutoCompleteExtender
    End Class
End Namespace
