'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace TrackITKTS

    Partial Public Class rptBranchPlantReconciliation

        '''<summary>
        '''sm1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sm1 As Global.System.Web.UI.ScriptManager

        '''<summary>
        '''addATSUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents addATSUsers As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TABLE2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TABLE2 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''TABLE4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TABLE4 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCompanyName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCompanyName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlCompanyName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCompanyName As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''rfvCompanyName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvCompanyName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlBranchPlantCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlBranchPlantCode As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''btn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btn As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''TABLE1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TABLE1 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''CrystalReportViewer1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CrystalReportViewer1 As Global.CrystalDecisions.Web.CrystalReportViewer

        '''<summary>
        '''summary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents summary As Global.System.Web.UI.WebControls.ValidationSummary
    End Class
End Namespace
