'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace TrackITKTS

    Partial Public Class rptTotalKegPopulation

        '''<summary>
        '''chkSession control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSession As Global.KEG_X.TrackITKTS.chkUserpresent

        '''<summary>
        '''sm1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sm1 As Global.System.Web.UI.ScriptManager

        '''<summary>
        '''addATSUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents addATSUsers As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TABLE2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TABLE2 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''MENULIST control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MENULIST As Global.KEG_X.TrackITKTS.Controls_MenuList

        '''<summary>
        '''TABLE4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TABLE4 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rcbCompany control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbCompany As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''rfvrdcCmpnny control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvrdcCmpnny As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Label4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''hdfItemIDs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfItemIDs As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''rcbItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbItems As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''btnShow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnShow As Global.Telerik.Web.UI.RadButton

        '''<summary>
        '''TABLE1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TABLE1 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''CrystalReportViewer1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CrystalReportViewer1 As Global.CrystalDecisions.Web.CrystalReportViewer

        '''<summary>
        '''summary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents summary As Global.System.Web.UI.WebControls.ValidationSummary
    End Class
End Namespace
